In [1]:
import numpy as np

In [4]:
# Importing CSV file

import csv
f = open("datasets/nyc_taxis.csv", "r")
taxi_list = list(csv.reader(f)) # 2D array

# remove the header row
taxi_list = taxi_list[1:]

# converting all values to floats
converted_taxi_list = []
for row in taxi_list:
    converted_row = []
    for item in row:
        converted_row.append(float(item))
    converted_taxi_list.append(converted_row)

converted_taxi_list

[[2016.0,
  1.0,
  1.0,
  5.0,
  0.0,
  2.0,
  4.0,
  21.0,
  2037.0,
  52.0,
  0.8,
  5.54,
  11.65,
  69.99,
  1.0],
 [2016.0,
  1.0,
  1.0,
  5.0,
  0.0,
  2.0,
  1.0,
  16.29,
  1520.0,
  45.0,
  1.3,
  0.0,
  8.0,
  54.3,
  1.0],
 [2016.0,
  1.0,
  1.0,
  5.0,
  0.0,
  2.0,
  6.0,
  12.7,
  1462.0,
  36.5,
  1.3,
  0.0,
  0.0,
  37.8,
  2.0],
 [2016.0,
  1.0,
  1.0,
  5.0,
  0.0,
  2.0,
  6.0,
  8.7,
  1210.0,
  26.0,
  1.3,
  0.0,
  5.46,
  32.76,
  1.0],
 [2016.0,
  1.0,
  1.0,
  5.0,
  0.0,
  2.0,
  6.0,
  5.56,
  759.0,
  17.5,
  1.3,
  0.0,
  0.0,
  18.8,
  2.0],
 [2016.0,
  1.0,
  1.0,
  5.0,
  0.0,
  4.0,
  2.0,
  21.45,
  2004.0,
  52.0,
  0.8,
  0.0,
  52.8,
  105.6,
  1.0],
 [2016.0,
  1.0,
  1.0,
  5.0,
  0.0,
  2.0,
  6.0,
  8.45,
  927.0,
  24.5,
  1.3,
  0.0,
  6.45,
  32.25,
  1.0],
 [2016.0,
  1.0,
  1.0,
  5.0,
  0.0,
  2.0,
  6.0,
  7.3,
  731.0,
  21.5,
  1.3,
  0.0,
  0.0,
  22.8,
  2.0],
 [2016.0,
  1.0,
  1.0,
  5.0,
  0.0,
  2.0,
  5.0,
  36.3,
  2562.0,
  1

ndarrays:
- N-dimensional arrays
- make vectorization possible
- faster due to SIMD

In [6]:
# Convert list to numpy array
np.array([10, 20, 30])

array([10, 20, 30])

In [7]:
# Convert 2D array to numpy array
taxi = np.array(converted_taxi_list)
taxi

array([[2.016e+03, 1.000e+00, 1.000e+00, ..., 1.165e+01, 6.999e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 8.000e+00, 5.430e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 0.000e+00, 3.780e+01,
        2.000e+00],
       ...,
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 5.000e+00, 6.334e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 8.950e+00, 4.475e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 0.000e+00, 5.484e+01,
        2.000e+00]])

In [9]:
# Read CSV directly to numpy ndarray
# Numpy automatically guesses data type
# skip_header skips given no. of rows from the top

taxi = np.genfromtxt('datasets/nyc_taxis.csv', delimiter=',', skip_header=1)
taxi

array([[2.016e+03, 1.000e+00, 1.000e+00, ..., 1.165e+01, 6.999e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 8.000e+00, 5.430e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 0.000e+00, 3.780e+01,
        2.000e+00],
       ...,
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 5.000e+00, 6.334e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 8.950e+00, 4.475e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 0.000e+00, 5.484e+01,
        2.000e+00]])

In [10]:
taxi.dtype

dtype('float64')

In [11]:
# Check the dimensions of the array
taxi_shape = taxi.shape
print(taxi_shape)

(2013, 15)


**Indexing**:

For 1D array:
ndarray[index]

For 2D array: 
- Select single value: ndarray[row_index,column_index]
- Select entire row: ndarray[row_index]

We can use slicing with indexing too.

In [12]:
# Selecting single row
taxi[0]

array([2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
       4.000e+00, 2.100e+01, 2.037e+03, 5.200e+01, 8.000e-01, 5.540e+00,
       1.165e+01, 6.999e+01, 1.000e+00])

In [13]:
# Select range of rows
taxi[300:303]

array([[2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 5.000e+00, 3.000e+00,
        1.000e+00, 7.940e+00, 9.610e+02, 2.350e+01, 1.300e+00, 0.000e+00,
        4.960e+00, 2.976e+01, 1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 5.000e+00, 2.000e+00,
        1.000e+00, 2.031e+01, 1.661e+03, 5.400e+01, 1.300e+00, 0.000e+00,
        1.382e+01, 6.912e+01, 1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 5.000e+00, 2.000e+00,
        4.000e+00, 1.860e+01, 2.460e+03, 5.200e+01, 8.000e-01, 0.000e+00,
        0.000e+00, 5.280e+01, 2.000e+00]])

In [14]:
# Select particular columns
taxi[:, [1, 4, 7]]

array([[ 1.  ,  0.  , 21.  ],
       [ 1.  ,  0.  , 16.29],
       [ 1.  ,  0.  , 12.7 ],
       ...,
       [ 6.  ,  5.  , 17.48],
       [ 6.  ,  5.  , 12.76],
       [ 6.  ,  5.  , 17.54]])

In [15]:
# Select range of rows and columns
taxi[300:303, 0:2]

array([[2.016e+03, 1.000e+00],
       [2.016e+03, 1.000e+00],
       [2.016e+03, 1.000e+00]])

In [16]:
# Select particular value
taxi[21, 5]

4.0

**Vectorized operations**
- Faster and efficient
- an operation between a ndarray and a single value results in a new ndarray

In [17]:
np.array([2,4,6,8]) + 10

array([12, 14, 16, 18])

In [20]:
# Adding two columns
fare_amount = taxi[:,9]
fees_amount = taxi[:,10]
fare_amount + fees_amount

array([52.8, 46.3, 37.8, ..., 52.8, 35.8, 49.3])

In [22]:
# Finding average speed of travel

trip_distance_miles = taxi[:,7]
trip_length_seconds = taxi[:,8]

# Convert seconds to hours
trip_length_hours = trip_length_seconds / 3600

# Average speed (miles per hour) for each trip
trip_mph = trip_distance_miles / trip_length_hours
trip_mph

array([37.11340206, 38.58157895, 31.27222982, ..., 22.29907867,
       42.41551247, 36.90473407])

Some more vectorized operations:
- ndarray.min() to calculate the minimum value
- ndarray.max() to calculate the maximum value
- ndarray.mean() to calculate the mean or average value
- ndarray.sum() to calculate the sum of the values

In [23]:
# Mean of avg speed of all trips
trip_mph.mean()

169.98315083655157

Some of these methods are also used as functions.

In [24]:
np.mean(trip_mph)

169.98315083655157

**Statistics for 2D arrays**

Row: axis=1, Column: axis=0

In [18]:
# Single maximum from 2D array
taxi.max()

85360.0

In [25]:
# Max in each row
taxi.max(axis=1)

array([2037., 2016., 2016., ..., 2822., 2016., 2016.])

In [26]:
# Max in each column
taxi.max(axis=0)

array([2.0160e+03, 6.0000e+00, 3.0000e+01, 7.0000e+00, 5.0000e+00,
       6.0000e+00, 7.0000e+00, 3.7300e+01, 8.5360e+04, 1.1700e+02,
       5.3000e+00, 2.3580e+01, 5.2800e+01, 1.4188e+02, 4.0000e+00])

In [27]:
# Finding total fare
taxi_5 = taxi[0:5]
# select these columns (9-12): fare_amount, fees_amount, tolls_amount, tip_amount

fare_components = taxi_5[:, 9:13]
fare_sums = fare_components.sum(axis=1)
print(fare_sums)

# Comparing to actual total fare
fare_totals = taxi_5[:, 13]

fare_sums == fare_totals

[69.99 54.3  37.8  32.76 18.8 ]


array([ True,  True,  True,  True,  True])

**Boolean operations**:

In [22]:
# Vectorized boolean operations
a = np.array([1, 2, 3, 4, 5])
a_bool = a < 3
a_bool

array([ True,  True, False, False, False])

In [23]:
# Boolean indexing
# The Boolean array acts as a filter

a[a_bool]

array([1, 2])

In [24]:
# Boolean array must have the same length as the dimension you're indexing
b = np.array([[1, 2],
              [5, 6],
              [10, 14]
             ])

# To apply condition to each row, length of boolean array is equal to number of rows
bool_1 = [True, False, True]
print(b[bool_1])

# To apply condition to each columns, length of boolean array is equal to number of columns
bool_2 = [False, True]
print(b[:, bool_2])

[[ 1  2]
 [10 14]]
[[ 2]
 [ 6]
 [14]]


In [25]:
# Find number of taxi rides in the month of February

pickup_month = taxi[:,1]
february_bool = pickup_month == 2
february = pickup_month[february_bool]
february.shape[0]

176

In [26]:
# Find the pickup_location_code, dropoff_location_code, trip_distance, and trip_length 
# of trips with average speeds greater than 20,000 mph

trip_mph_bool = trip_mph > 20000

trips_over_20000_mph = taxi[trip_mph_bool, 5:9]
trips_over_20000_mph

# The high values of speed are due to the very low values for trip_length (secs)

array([[ 2. ,  2. , 23. ,  1. ],
       [ 2. ,  2. , 19.6,  1. ],
       [ 2. ,  2. , 16.7,  2. ],
       [ 3. ,  3. , 17.8,  2. ],
       [ 2. ,  2. , 17.2,  2. ],
       [ 3. ,  3. , 16.9,  3. ],
       [ 2. ,  2. , 27.1,  4. ]])

In [27]:
# Find trip details for tips greater than 50

tip_amount = taxi[:,12]
tip_bool = tip_amount > 50
top_tips = taxi[tip_bool, 5:14]
top_tips
# Only one such trip

array([[4.000e+00, 2.000e+00, 2.145e+01, 2.004e+03, 5.200e+01, 8.000e-01,
        0.000e+00, 5.280e+01, 1.056e+02]])

**Modify value in ndarray: <br>**
ndarray[location_of_values] = new_value

In [28]:
# 1D array
a = np.array(['red','blue','black','blue','purple'])
a[0] = 'orange'
a

array(['orange', 'blue', 'black', 'blue', 'purple'], dtype='<U6')

In [29]:
# Assign multiple values at once
a[3:] = 'pink'
a

array(['orange', 'blue', 'black', 'pink', 'pink'], dtype='<U6')

In [30]:
# 2D array
ones = np.array([[1, 1, 1, 1, 1],
                 [1, 1, 1, 1, 1],
                 [1, 1, 1, 1, 1]])
ones[1,2] = 99
ones

array([[ 1,  1,  1,  1,  1],
       [ 1,  1, 99,  1,  1],
       [ 1,  1,  1,  1,  1]])

In [31]:
# Change all values in a row
ones[0] = 42
ones

array([[42, 42, 42, 42, 42],
       [ 1,  1, 99,  1,  1],
       [ 1,  1,  1,  1,  1]])

In [32]:
# Change all values in a column
ones[:,3] = 77
ones

array([[42, 42, 42, 77, 42],
       [ 1,  1, 99, 77,  1],
       [ 1,  1,  1, 77,  1]])

In [33]:
# Creating copy of taxi to modify
taxi2 = taxi.copy()

# Change single value
taxi2[1066, 5] = 1

# Change a column of values
taxi2[:, 0] = 16

# Change a value to the mean of that column
taxi2[550, 7] = taxi2[:, 7].mean()

In [34]:
# Wherever total amount is less than 0, make it 0

total_amount = taxi2[:, 13]
total_amount_bool = total_amount < 0
total_amount[total_amount_bool] = 0
taxi2[:, 13] = total_amount

In [49]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
b[b>4] = 20
b

array([[ 1,  2,  3],
       [ 4, 20, 20],
       [20, 20, 20]])

Use a 1D boolean array to perform assignment on a 2D array <br>
Syntax: <br>
bool = array[:, column_for_comparison] == value_for_comparison <br>
array[bool, column_for_assignment] = new_value

In [52]:
# c[:, 1] > 2 - Boolean of second column elements greater than 2
# Used the boolean array as row selected and choose second columns

c = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
c_bool = c[:, 1] > 2 # Gives [F, T, T]
c[c_bool, 1] = 40 # Selects F,T,T rows from second columns => 5 and 8
c

array([[ 1,  2,  3],
       [ 4, 40,  6],
       [ 7, 40,  9]])

In [54]:
# Add a column (index 15) of zeroes to taxi(copy). 
# Set it to 1 wherever the pickup location (column 5) is an airport (2, 3 or 5)

zeros = np.zeros([taxi2.shape[0], 1])
taxi2 = np.concatenate([taxi2, zeros], axis=1)

taxi2[taxi2[:, 5] == 2, 15] = 1
taxi2[taxi2[:, 5] == 3, 15] = 1
taxi2[taxi2[:, 5] == 5, 15] = 1

print(taxi2[:, 15]==1)

[ True  True  True ...  True  True  True]


In [55]:
# Calculate how many trips were to each airport
# Destination code: column 6

jfk_count = taxi[taxi[:, 6] == 2].shape[0]

laguardia_count = taxi[taxi[:, 6] == 3].shape[0]

newark_count = taxi[taxi[:, 6] == 5].shape[0]

In [70]:
# Find mean distance, time and amount

# speed = distance by length(time)
trip_mph = taxi[:,7] / (taxi[:,8] / 3600)

# Removing outliers
cleaned_taxi = taxi[trip_mph < 100]

mean_distance = np.mean(cleaned_taxi[:, 7])
mean_length = np.mean(cleaned_taxi[:, 8])
mean_total_amount = np.mean(cleaned_taxi[:, 13])